spring:
  application:
    name: account-service
  config:
    import: configserver:http://${CONFIG_SERVER_CONTAINER_NAME}:${CONFIG_SERVER_PORT}
  cloud:
    config:
      fail-fast: true
  liquibase:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwkSetUri: http://${KEYCLOAK_HOST_NAME}:8080/realms/demo/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: spring-with-test-scope