input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  # Example: Add metadata or modify logs if needed
#  mutate {
#    add_field => { "service" => "my-java-service" }
#  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[service]}-%{[@version]}-%{+YYYY.MM.dd}"
    document_id => "%{[@timestamp]}-%{[host]}-%{[thread_name]}"
  }
}