eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_CONTAINER_NAME}:${EUREKA_SERVER_PORT}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, refresh
#  health:
#    readiness-state:
#      enabled: true
#    liveness-state:
#      enabled: true
#  endpoint:
#    health:
#      probes:
#        enabled: true

jwt:
  auth:
    converter:
      resource-id: ${KEYCLOAK_CLIENT_NAME}

spring:
  cloud:
    config:
      overrideSystemProperties: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwkSetUri: ${OIDC_ISSUER_URI_OUTER}/protocol/openid-connect/certs

logging:
  config: classpath:logback-spring.xml