spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: ticket-service
          uri: lb:http://TICKET-SERVICE
          predicates:
            - Path=/api/v1/tickets/**
        - id: account-service
          uri: lb:http://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/accounts/v3/api-docs,/api/v1/customer/**,/api/v1/currency/**
server:
  port: ${GATEWAY_SERVER_PORT}

eureka:
  instance:
    hostname: ${GATEWAY_SERVICE_CONTAINER_NAME}
  client:
    registerWithEureka: true
    fetchRegistry: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Gateway Service
      - url: /api/v1/orders/v3/api-docs
        name: Order Service
      - url: /api/v1/tickets/v3/api-docs
        name: Ticket Service
      - url: /api/v1/accounts/v3/api-docs
        name: Account Service